routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReportControllerCustom;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


// Route::middleware('guest')->group(function () {
//     Route::get('/', fn() => view('auth.login'))->name('home');
// });
Route::get('/', [HomeController::class, 'index'])->name('home');

// Route public report viewer
// Route::view('/report/detail', 'landing-page.report');
Route::get('public/report/{report}', [ReportControllerCustom::class, 'showPublicReport'])->name('public.report.show');

Route::middleware('auth')->group(function () {

    // Route admin dan guru

    // Route Report Unread
    Route::get('report/unread', [ReportControllerCustom::class, 'unreadReport'])->name('report.unreadReport');

    // Report Progressing
    Route::get('report/progressing', [ReportControllerCustom::class, 'progressingReport'])->name('report.progressingReport');

    // Route Report Finish
    Route::get('report/selesai', [ReportControllerCustom::class, 'selesaiReport'])->name('report.selesaiReport');

    // Route Report
    Route::resource('report', ReportController::class);
    Route::get('report/{report}/process', [ReportController::class, 'processingReport'])->name('report.processingReport');
    Route::get('report/{report}/finish', [ReportController::class, 'finishReport'])->name('report.finishReport');
    Route::post('report/{report}/comment', [ReportController::class, 'commentReport'])->name('report.commentReport');

    // Route Management user 
    Route::middleware('role:admin')->group(function () {
        Route::get('management/data-pengguna', [UserController::class, 'index'])->name('management');
        Route::post('management/data-pengguna/{user}/update', [UserController::class, 'updateRole'])->name('management.updateRole');
        Route::delete('management/data-pengguna/{user}/delete', [UserController::class, 'destroy'])->name('management.delete');
    });
});

Route::middleware(['auth', 'verified'])->group(function () {
});

require __DIR__ . '/auth.php';

app/Models/Report.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\ReportReciver;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Models\ReportAttachment;
use Illuminate\Support\Str;


class Report extends Model
{
    use HasFactory;
    use HasUuids;

    protected $with = ['sender', 'reciver', 'attachments'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'sender_id',
        'subject',
        'sessage',
        'status',
        'soomType',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'Sender_id' => 'integer',
        'Status' => 'string',
        'RoomType' => 'string',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'deleted_at',
    ];

    /**
     * Relationship: Sebuah laporan dimiliki oleh satu pengirim (User).
     */
    public function sender()
    {
        return $this->belongsTo(User::class, 'sender_id');
    }

    /**
     * Relationship: Sebuah laporan dapat memiliki banyak penerima (reciver).
     */
    public function reciver()
    {
        return $this->hasMany(ReportReciver::class, 'report_id');
    }

    /**
     * Relationship: Sebuah laporan dapat memiliki banyak lampiran (Attachments).
     */
    public function attachments()
    {
        return $this->hasMany(ReportAttachment::class, 'report_id');
    }

    public static function getAnonymousName(): string
    {
        return Str::random(10);
    }

    public function getCreatedAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->diffForHumans();
    }

    public function getUpdatedAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->diffForHumans();
    }

    public function comments()
    {
        return $this->hasMany(ReportComment::class, 'report_id');
    }

    public function publicView()
    {
        return $this->hasOne(ReportPublicView::class, 'report_id');
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use Throwable;
use App\Models\User;
use App\Models\Report;
use Illuminate\Http\Request;
use App\Models\ReportComment;
use App\Models\ReportReciver;
use function Termwind\render;
use App\Models\ReportAttachment;

use App\Http\Controllers\Controller;

use function Laravel\Prompts\select;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;
use Database\Factories\ReportFactory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Redirect;
use App\Http\Requests\StoreReportRequest;
use App\Http\Requests\UpdateReportRequest;

class ReportController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $title = 'Semua Laporan';
        $paginateControl = 30;

        $getLaporan = Report::orderByDesc('created_at')
            ->without('attachments')
            ->where(function ($query) {
                $query->where('sender_id', Auth::user()->id)
                    ->orWhereHas('reciver', function ($query) {
                        $query->where('reciver_id', Auth::user()->id);
                    });
            })
            ->paginate($paginateControl);
        $getLaporan->each(function ($laporan) {
            $recivers = User::whereIn('id', $laporan->reciver->pluck('reciver_id'))->get();
            $nameRecivers = $recivers->pluck('name')->toArray();
            $avatarRecivers = $recivers->pluck('avatar_url')->toArray();
            $emailRecivers = $recivers->pluck('email')->toArray();

            $laporan->avatar_recivers = $avatarRecivers[0] ?? null;
            $laporan->email_recivers = $emailRecivers[0] ?? null;
            $laporan->reciver_names = '';

            if (count($nameRecivers) > 1) {
                $laporan->reciver_names = implode(' & ', array_slice($nameRecivers, 0, 1)); // Tambahkan satu nama penerima pertama
                $laporan->reciver_names .= ' & ' . (count($nameRecivers) - 1) . ' others'; // Tambahkan jumlah penerima lainnya
            } else {
                // Jika hanya ada satu penerima, gunakan namanya langsung
                $laporan->reciver_names = $nameRecivers[0] ?? null;
            }
        });
        // dd($getLaporan);
        return view('reports.index', compact('getLaporan', 'title'));
    }


    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {

        $dataGuru = User::where('role_id', 2)->select('id', 'name')->get();
        // dd($dataGuru);
        return view('reports.create', compact('dataGuru'));
    }

    /**
     * Store a newly created resource in storage.
     */
    // public function store(Request $request) : RedirectResponse
    public function store(StoreReportRequest $request): RedirectResponse
    {
        try {
            $request->validated([
                'Sender_id' => 'required',
                'recipient' => 'required',
                'Lokasi' => 'required',
                'Message' => 'required',
                'roomType' => 'required',
                'attachment.*' => 'nullable'
            ]);

            if ($request->roomType[0] === 'anonim') {
                $anonimName = Report::getAnonymousName();
            }
        } catch (Throwable $e) {
            return Redirect::back()->with('error', $e->getMessage());
        }
        // dd($request->all());
        try {
            // Remove duplicate recipient IDs
            $uniqueRecipients = array_unique($request->recipient);
            // Create a new Report
            $report = new Report();
            $report->sender_id = $request->Sender_id;
            $report->anonymous_name = $anonimName ?? null;
            $report->lokasi = $request->Lokasi;
            $report->message = $request->Message;
            $report->roomType = $request->roomType[0];
            $report->save();

            // Attach unique recipients to the report
            foreach ($uniqueRecipients as $recipient) {
                $reportRecipient = new ReportReciver();
                $reportRecipient->report_id = $report->id;
                $reportRecipient->reciver_id = $recipient;
                $reportRecipient->save();
            }

            if ($request->hasFile('attachment')) {
                foreach ($request->file('attachment') as $file) {
                    $filename = $file->hashName();
                    $file->storeAs('public/uploads', $filename);

                    $attachment = new ReportAttachment();
                    $attachment->report_id = $report->id;
                    $attachment->filename = '/storage/uploads/' . $filename;
                    $attachment->save();
                }
            }

            return Redirect::route('report.index')->with('success', 'Laporan berhasil dikirim');
        } catch (Throwable $e) {
            return Redirect::back()->with('error', $e->getMessage());
        }
    }


    /**
     * Display the specified resource.
     */
    public function show($uuid)
    {
        // Fetch the report with the specified UUID and its reciver relationship
        $detailLaporan = Report::where('id', $uuid)->with('reciver', 'comments')->get();

        if ($detailLaporan->first()->status === 'terkirim') {
            if ($detailLaporan->first()->sender_id !== Auth::user()->id) {
                $detailLaporan->first()->update(['status' => 'dibaca']);
            }
        }
        $detailLaporan->each(function ($laporan) {
            $recivers = User::whereIn('id', $laporan->reciver->pluck('reciver_id'))->get();
            // $comments = ReportComment::where('report_id', $laporan->id)->get();
            $nameRecivers = $recivers->pluck('name')->toArray();
            $avatarRecivers = $recivers->pluck('avatar_url')->toArray();
            $emailRecivers = $recivers->pluck('email')->toArray();

            // $laporan->comments = $comments;
            $laporan->email_recivers = $emailRecivers[0] ?? null;
            $laporan->avatar_recivers = $avatarRecivers[0] ?? null;
            $laporan->reciver_names = '';

            // Jika ada lebih dari satu penerima, tambahkan '& x others' di akhir
            if (count($nameRecivers) > 1) {
                $laporan->reciver_names = implode(' & ', array_slice($nameRecivers, 0, 1)); // Tambahkan satu nama penerima pertama
                $laporan->reciver_names .= ' & ' . (count($nameRecivers) - 1) . ' others'; // Tambahkan jumlah penerima lainnya
            } else {
                // Jika hanya ada satu penerima, gunakan namanya langsung
                $laporan->reciver_names = $nameRecivers[0] ?? null;
            }
        });


        $detailLaporan = $detailLaporan->first();
        // dd($detailLaporan);

        if (!$detailLaporan) {
            // Handle the case where the report is not found
            return response()->json(['error' => 'Report not found'], 404);
        }

        // Render the view 'layouts.detailReportOpen' with the data '$detailLaporan'
        // dd($detailLaporan);
        return view('layouts.detailLaporanTab', compact('detailLaporan'));
    }

    public function processingReport(Report $report)
    {
        // dd($report);
        $report->update(['status' => 'diproses']);

        return Redirect::route('report.progressingReport')->with('success', 'Laporan berhasil diproses');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Report $report)
    {
        // dd($report);
        $dataGuru = User::where('role_id', 2)->select('id', 'name')->get();

        // dd($dataGuru);
        return view('reports.edit', compact('dataGuru', 'report'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateReportRequest $request, Report $report)
    {
        // dd($request->all());

        try {
            $request->validated([
                'Sender_id' => 'required',
                'recipient' => 'required',
                'Lokasi' => 'required',
                'Message' => 'required',
                'roomType' => 'required',
                'attachment.*' => 'nullable'
            ]);

            if ($request->roomType[0] === 'anonim') {
                $anonimName = Report::getAnonymousName();
            }

            // dd($anonimName);

            // dd($request->all());
        } catch (Throwable $e) {
            return Redirect::back()->with('error', $e->getMessage());
        }

        try {
            // Remove duplicate recipient IDs
            $uniqueRecipients = array_unique($request->recipient);
            // Update the Report
            $report->sender_id = $request->Sender_id;
            $report->lokasi = $request->Lokasi;
            $report->message = $request->Message;
            $report->roomType = $request->roomType[0];
            $report->save();

            // Attach unique recipients to the report
            $report->reciver()->delete();

            foreach ($uniqueRecipients as $recipient) {
                $reportRecipient = new ReportReciver();
                $reportRecipient->report_id = $report->id;
                $reportRecipient->reciver_id = $recipient;
                $reportRecipient->save();
            }

            if ($request->hasFile('attachment')) {
                $report->attachments()->delete();
                $oldAttachments = $report->attachments;

                // Hapus setiap foto lama dari penyimpanan
                foreach ($oldAttachments as $oldAttachment) {
                    Storage::delete(str_replace('/storage', 'public', $oldAttachment->filename));
                }
                foreach ($request->file('attachment') as $file) {
                    $filename = $file->hashName();

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/reports/create.blade.php
<x-app-layout>
    <div class="p-2 absolute bottom-2 w-[96%] lg:w-[50%] right-3 sm:right-5 z-50 hidden">
        <div class="bg-gray-200 p-4 rounded-lg shadow-lg">
            <div id="preview" class="flex flex-wrap gap-2 overflow-y-auto h-[400px]"></div>
        </div>
    </div>
    <div name="header" class="px-3 py-2 sm:px-6 sm:py-4 md:p-4 mb-5">
        <!-- Page Alerts -->
        @include('components.alerts')
        <h1 class="font-semibold text-2xl md:text-3xl mb-2 font-system-ui capitalize">
            {{ __('Laporan') }}
        </h1>
        <p class="text-sm mb-4 text-gray-400 dark:text-gray-400 font-system-ui capitalize ">
            {{ __('Daftar Seluruh Data Laporan Siswa SMPN 18 Malang') }}</p>
        <div class="border-b border-gray-300 my-5"></div>
        <!-- Page mother -->
        <div class="min-h-content">

            <!-- Page wrapper -->
            <form action="{{ route('report.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="Sender_id" value="{{ auth()->id() }}">
                <div
                    class="p-4 sm:p-8 bg-gray-50 border-gray-100 dark:bg-darker border-2 dark:border-blue-600 shadow rounded-xl drop-shadow-lg">
                    <div class="text-2xl font-bold text-gray-600 dark:text-white">
                        Buat Laporan Anda
                    </div>
                    <div class="max-w-full">
                        <div id="additionalInputsContainer" class="my-4 flex flex-col sm:flex-row gap-4">

                            <div class="col-span-4">
                                <legend class="text-sm font-semibold leading-6 text-gray-900 dark:text-white">Choose
                                    Your Type Report
                                </legend>
                                <p class="mt-1 text-sm leading-6 text-gray-600 dark:text-gray-300">Pilihan Anda
                                    menentukan type laporan
                                    anda tolong bijaklah dalam memilih pilihan anda.</p>
                            </div>
                            <fieldset class="col-span-4">
                                <div class="space-y-6">
                                    <div class="flex items-center gap-x-3">
                                        <input id="laporan-publik" name="roomType[]" value="public" type="radio"
                                            required class="h-4 w-4 border-gray-300 text-biru focus:ring-biru">
                                        <label for="laporan-publik"
                                            class="block text-sm font-medium leading-6 text-gray-900 dark:text-white">Laporan
                                            Publik
                                            <p class="text-gray-500 text-xs font-normal dark:text-gray-300">Nama dan
                                                laporan Anda dapat dilihat publik.</p>
                                        </label>
                                    </div>
                                    <div class="flex items-center gap-x-3">
                                        <input id="laporan-privat" name="roomType[]" value="private" type="radio"
                                            required class="h-4 w-4 border-gray-300 text-biru focus:ring-biru">
                                        <label for="laporan-privat"
                                            class="block text-sm font-medium leading-6 text-gray-900 dark:text-white">Laporan
                                            Privat
                                            <p class="text-gray-500 font-normal text-xs dark:text-gray-300">Laporan Anda
                                                tidak dapat dilihat publik.
                                            </p>
                                        </label>
                                    </div>
                                    <div class="flex items-center gap-x-3">
                                        <input id="laporan-anonim" name="roomType[]" value="anonim" type="radio"
                                            required class="h-4 w-4 border-gray-300 text-biru focus:ring-biru">
                                        <label for="laporan-anonim"
                                            class="block text-sm font-medium leading-6 text-gray-900 dark:text-white">Laporan
                                            Anonymus
                                            <p class="text-gray-500 font-normal text-xs dark:text-gray-300">Nama Anda
                                                akan disamarkan dan laporan tidak dapat dilihat publik.</p>
                                        </label>
                                    </div>
                                </div>
                            </fieldset>
                        </div>

                        <div class="col-span-4 p-3 mt-2 bg-gray-100 dark:bg-[#0a2647] rounded-md w-full">
                            <div class="flex items-center align-middle">
                                <p class="text-sm text-gray-900 dark:text-white pt-2 ps-2">
                                    Pilih Penerima Laporan Anda / Pilih semua
                                <div class="flex text-center items-center ms-6">
                                    <input id="check_all" type="checkbox"
                                        class="w-4 h-4 mt-2 text-green-600 bg-gray-100 border-gray-300 rounded focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                    <label for="check_all" class="text-sm text-gray-900 dark:text-white pt-2 ps-2">Check
                                        All </label>
                                </div>
                            </div>
                            <div class="border-b border-gray-300 my-2"></div>
                            <div class="flex flex-wrap gap-2">
                                @foreach ($dataGuru as $guru)
                                    <div class="flex items-center me-4 mb-4 min-w-[18rem]">
                                        <input id="recipient_id_{{ $guru->id }}" type="checkbox"
                                            value="{{ $guru->id }}" name="recipient[]"
                                            class="w-6 h-6 text-green-600 bg-gray-100 border-gray-300 rounded focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                        <label for="recipient_id_{{ $guru->id }}"
                                            class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">{{ $guru->name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="mt-4">
                            <label for="Lokasi"
                                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Lokasi
                                Kejadian</label>
                            <input type="text" id="Lokasi" name="Lokasi" placeholder="Didepan Ruang 27"
                                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-[#0a2647] dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        </div>
                        <div class="my-2">
                            <div
                                class="w-full mb-4 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-700 dark:border-gray-600">
                                <div class="px-4 py-2 bg-white rounded-t-lg dark:bg-[#0a2647]">
                                    <label for="Message" class="sr-only">Tuliskan Keluhan Anda</label>
                                    <textarea id="Message" rows="12" name="Message"
                                        class="w-full px-0 text-sm text-gray-900 bg-white border-0 dark:bg-[#0a2647] focus:ring-0 dark:text-white dark:placeholder-gray-400"
                                        placeholder="Tuliskan Keluhan Anda..." required></textarea>
                                </div>
                                <div class="flex items-center justify-between px-3 py-2 border-t dark:border-gray-600">
                                    <button type="submit"
                                        class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">
                                        <svg class="w-3.5 h-3.5 text-white me-2" aria-hidden="true"
                                            xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16">
                                            <path
                                                d="m10.036 8.278 9.258-7.79A1.979 1.979 0 0 0 18 0H2A1.987 1.987 0 0 0 .641.541l9.395 7.737Z" />
                                            <path
                                                d="M11.241 9.817c-.36.275-.801.425-1.255.427-.428 0-.845-.138-1.187-.395L0 2.6V14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2.5l-8.759 7.317Z" />
                                        </svg>
                                        Kirim Keluhan
                                    </button>
                                    <div class="flex ps-0 space-x-1 rtl:space-x-reverse sm:ps-2">
                                        <div class="flex ps-0 space-x-1 rtl:space-x-reverse sm:ps-2">
                                            <label for="attachment"
                                                class="inline-flex justify-center items-center p-2 text-gray-500 rounded cursor-pointer hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600">
                                                <x-icon.attach-file class="w-4 h-4" aria-hidden="true"
                                                    viewBox="0 0 12 20" fill="none" />
                                                <span class="sr-only">Attach file</span>
                                            </label>
                                            <input id="attachment" type="file" name="attachment[]" class="hidden" accept="image/*" multiple onchange="previewFiles()">
                                        </div>
                                    </div>
                                </div>
                                <div class="p-2">
                                    <span id="show_name_file" class="hidden text-sm">Foto yang Anda pilih :</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script src="{{ asset('src/js/report.js') }}"></script>
</x-app-layout>